name: build

on:
  push:
    branches: [ "main", "feature/*", "fix/*", "refactor/*", "enhancement/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Compile project
      run: mvn compile
    - name: Execute tests
      run: mvn test
